/**
 * @copyright
 *
 * @file    dali2_spec_cmd_list.h
 * @author  Anton K.
 * @date    02 Sep 2021
 *
 * @brief   DALI-2 Application Controller.
 *          Special command list header file
 *          @ref DALI IEC 62386-102-2014
 */
#ifndef DALI2_SPEC_CMD_LIST_H_
#define DALI2_SPEC_CMD_LIST_H_

//! Special command list
typedef enum {
    DALI2_L_APP_SPEC_CMD_TERMINATE = 0xA1,
    DALI2_L_APP_SPEC_CMD_DTR0 = 0xA3,
    DALI2_L_APP_SPEC_CMD_INITIALISE = 0xA5,
    DALI2_L_APP_SPEC_CMD_RANDOMISE = 0xA7,
    DALI2_L_APP_SPEC_CMD_COMPARE = 0xA9,
    DALI2_L_APP_SPEC_CMD_WITHDRAW = 0xAB,
    DALI2_L_APP_SPEC_CMD_PING = 0xAD,
    DALI2_L_APP_SPEC_CMD_SEARCHADDRH = 0xB1,
    DALI2_L_APP_SPEC_CMD_SEARCHADDRM = 0xB3,
    DALI2_L_APP_SPEC_CMD_SEARCHADDRL = 0xB5,
    DALI2_L_APP_SPEC_CMD_PROGRAM_SHORT_ADDRESS = 0xB7,
    DALI2_L_APP_SPEC_CMD_VERIFY_SHORT_ADDRESS = 0xB9,
    DALI2_L_APP_SPEC_CMD_QUERY_SHORT_ADDRESS = 0xBB,
    DALI2_L_APP_SPEC_CMD_ENABLE_DEVICE_TYPE = 0xC1,
    DALI2_L_APP_SPEC_CMD_DTR1 = 0xC3,
    DALI2_L_APP_SPEC_CMD_DTR2 = 0xC5,
    DALI2_L_APP_SPEC_CMD_WRITE_MEMORY_LOCATION_DTR1_DTR0 = 0xC7,
    DALI2_L_APP_SPEC_CMD_WRITE_MEMORY_LOCATION_NO_REPLY_DTR1_DTR0 = 0xC9
} DALI2_L_APP_SPEC_CMD_T;

#endif /* DALI2_SPEC_CMD_LIST_H_ */
