/**
 * @copyright
 *
 * @file    dali2_std_cmd_list.h
 * @author  Anton K.
 * @date    02 Sep 2021
 *
 * @brief   DALI-2 Application Controller.
 *          Standard command list header file
 *          @ref DALI IEC 62386-102-2014
 */
#ifndef DALI2_STD_CMD_LIST_H_
#define DALI2_STD_CMD_LIST_H_

//! Standard command list
typedef enum {
    DALI2_L_APP_STD_CMD_OFF = 0x00,
    DALI2_L_APP_STD_CMD_UP,
    DALI2_L_APP_STD_CMD_DOWN,
    DALI2_L_APP_STD_CMD_STEP_UP,
    DALI2_L_APP_STD_CMD_STEP_DOWN,
    DALI2_L_APP_STD_CMD_RECALL_MAX_LEVEL,
    DALI2_L_APP_STD_CMD_RECALL_MIN_LEVEL,
    DALI2_L_APP_STD_CMD_STEP_DOWN_AND_OFF,
    DALI2_L_APP_STD_CMD_ON_AND_STEP_UP,
    DALI2_L_APP_STD_CMD_ENABLE_DAPC_SEQUENCE,
    DALI2_L_APP_STD_CMD_GO_TO_LAST_ACTIVE_LEVEL,

    DALI2_L_APP_STD_CMD_GO_TO_SCENE = 0x10,

    DALI2_L_APP_STD_CMD_RESET = 0x20,
    DALI2_L_APP_STD_CMD_STORE_ACTUAL_LEVEL_IN_DTR0,
    DALI2_L_APP_STD_CMD_SAVE_PERSISTENT_VARIABLES,
    DALI2_L_APP_STD_CMD_SET_OPERATING_MODE,
    DALI2_L_APP_STD_CMD_RESET_MEMORY_BANK,
    DALI2_L_APP_STD_CMD_IDENTIFY_DEVICE,

    DALI2_L_APP_STD_CMD_SET_MAX_LEVEL_DTR0 = 0x2A,
    DALI2_L_APP_STD_CMD_SET_MIN_LEVEL_DTR0,
    DALI2_L_APP_STD_CMD_SET_SYSTEM_FAILURE_LEVEL_DTR0,
    DALI2_L_APP_STD_CMD_SET_POWER_ON_LEVEL_DTR0,
    DALI2_L_APP_STD_CMD_SET_FADE_TIME_DTR0,
    DALI2_L_APP_STD_CMD_SET_FADE_RATE_DTR0,
    DALI2_L_APP_STD_CMD_SET_EXTENDED_FADE_TIME_DTR0,

    DALI2_L_APP_STD_CMD_SET_SCENE_DTR0 = 0x40,
    DALI2_L_APP_STD_CMD_REMOVE_FROM_SCENE = 0x50,
    DALI2_L_APP_STD_CMD_ADD_TO_GROUP = 0x60,
    DALI2_L_APP_STD_CMD_REMOVE_FROM_GROUP = 0x70,

    DALI2_L_APP_STD_CMD_SET_SHORT_ADDRESS_DTR0 = 0x80,
    DALI2_L_APP_STD_CMD_ENABLE_WRITE_MEMORY,

    DALI2_L_APP_STD_CMD_QUERY_STATUS = 0x90,
    DALI2_L_APP_STD_CMD_QUERY_CONTROL_GEAR_PRESENT,
    DALI2_L_APP_STD_CMD_QUERY_LAMP_FAILURE,
    DALI2_L_APP_STD_CMD_QUERY_LAMP_POWER_ON,
    DALI2_L_APP_STD_CMD_QUERY_LIMIT_ERROR,
    DALI2_L_APP_STD_CMD_QUERY_RESET_STATE,
    DALI2_L_APP_STD_CMD_QUERY_MISSING_SHORT_ADDRESS,
    DALI2_L_APP_STD_CMD_QUERY_VERSION_NUMBER,
    DALI2_L_APP_STD_CMD_QUERY_CONTENT_DTR0,
    DALI2_L_APP_STD_CMD_QUERY_DEVICE_TYPE,
    DALI2_L_APP_STD_CMD_QUERY_PHYSICAL_MINIMUM,
    DALI2_L_APP_STD_CMD_QUERY_POWER_FAILURE,
    DALI2_L_APP_STD_CMD_QUERY_CONTENT_DTR1,
    DALI2_L_APP_STD_CMD_QUERY_CONTENT_DTR2,
    DALI2_L_APP_STD_CMD_QUERY_OPERATING_MODE,
    DALI2_L_APP_STD_CMD_QUERY_LIGHT_SOURCE_TYPE,

    DALI2_L_APP_STD_CMD_QUERY_ACTUAL_LEVEL,
    DALI2_L_APP_STD_CMD_QUERY_MAX_LEVEL,
    DALI2_L_APP_STD_CMD_QUERY_MIN_LEVEL,
    DALI2_L_APP_STD_CMD_QUERY_POWER_ON_LEVEL,
    DALI2_L_APP_STD_CMD_QUERY_SYSTEM_FAILURE_LEVEL,
    DALI2_L_APP_STD_CMD_QUERY_FADE_TIME_FADE_RATE,
    DALI2_L_APP_STD_CMD_QUERY_MANUFACTURER_SPECIFIC_MODE,
    DALI2_L_APP_STD_CMD_QUERY_NEXT_DEVICE_TYPE,
    DALI2_L_APP_STD_CMD_QUERY_EXTENDED_FADE_TIME,
    DALI2_L_APP_STD_CMD_QUERY_CONTROL_GEAR_FAILURE = 0xAA,

    DALI2_L_APP_STD_CMD_QUERY_SCENE_LEVEL = 0xB0,

    DALI2_L_APP_STD_CMD_QUERY_GROUPS_0_7 = 0xC0,
    DALI2_L_APP_STD_CMD_QUERY_GROUPS_8_15,
    DALI2_L_APP_STD_CMD_QUERY_RANDOM_ADDRESS_H,
    DALI2_L_APP_STD_CMD_QUERY_RANDOM_ADDRESS_M,
    DALI2_L_APP_STD_CMD_QUERY_RANDOM_ADDRESS_L,
    DALI2_L_APP_STD_CMD_READ_MEMORY_LOCATION_DTR1_DTR0,

    DALI2_L_APP_STD_CMD_APPLICATION_EXTENDED_COMMANDS = 0xE0,

    DALI2_L_APP_STD_CMD_QUERY_EXTENDED_VERSION_NUMBER = 0xFF
} DALI2_L_APP_STD_CMD_T;

#endif /* DALI2_STD_CMD_LIST_H_ */
